# Generated by Django 5.0.6 on 2024-07-03 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('caption', models.TextField(verbose_name='Izoh')),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='kino_photos/', verbose_name='Rasmi')),
                ('category', models.CharField(choices=[('films', 'films'), ('series', 'series'), ('animes', 'animes'), ('primieras', 'primieras')], default='primieras', max_length=25, verbose_name='Kategoriyasi')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Kalit/Kod')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
            },
        ),
        migrations.CreateModel(
            name='PartModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='part_photos/', verbose_name='Rasmi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('caption', models.TextField(verbose_name='Izoh')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='cinema.moviemodels', verbose_name='Kino')),
            ],
            options={
                'verbose_name': 'Kino qismi',
                'verbose_name_plural': 'Kino qismlari',
            },
        ),
        migrations.CreateModel(
            name='SeasonModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='season_photos/', verbose_name='Rasmi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('caption', models.TextField(verbose_name='Izoh')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fasl', to='cinema.partmodels')),
            ],
            options={
                'verbose_name': 'Kino fasli',
                'verbose_name_plural': 'Kino fasllari',
            },
        ),
    ]
